# Generated by Django 3.1.7 on 2021-03-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iot',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='iot',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='iot',
            name='status',
        ),
        migrations.RemoveField(
            model_name='iot',
            name='temperature',
        ),
        migrations.AddField(
            model_name='iot',
            name='information',
            field=models.JSONField(default={'humidity': 0, 'moisture': 0, 'temperature': 0}),
        ),
    ]
